# Generated by Django 5.0.4 on 2024-04-14 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingDisposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.PositiveSmallIntegerField(choices=[(0, 'Processing'), (1, 'Accepted'), (1, 'Rejected')])),
                ('note', models.CharField(max_length=200)),
                ('mail', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.incomingmail')),
            ],
            options={
                'verbose_name': 'IncomingDisposition',
                'verbose_name_plural': 'IncomingDispositions',
            },
        ),
        migrations.CreateModel(
            name='OutgoingDisposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.PositiveSmallIntegerField(choices=[(0, 'Processing'), (1, 'Accepted'), (1, 'Rejected')])),
                ('note', models.CharField(max_length=200)),
                ('mail', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.outgoingmail')),
            ],
            options={
                'verbose_name': 'OutgoingDisposition',
                'verbose_name_plural': 'OutgoingDispositions',
            },
        ),
    ]
