# Generated by Django 5.0.4 on 2024-04-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_incomingdisposition_user_outgoingdisposition_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingdisposition',
            name='information',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Processing'), (1, 'Accepted'), (2, 'Rejected')]),
        ),
        migrations.AlterField(
            model_name='outgoingdisposition',
            name='information',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Processing'), (1, 'Accepted'), (2, 'Rejected')]),
        ),
    ]
