# Generated by Django 5.0.4 on 2024-04-14 13:12

import app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_incomingdisposition_information_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incomingdisposition',
            options={'verbose_name': 'Incoming Disposition', 'verbose_name_plural': 'Incoming Dispositions'},
        ),
        migrations.AlterModelOptions(
            name='incomingmail',
            options={'verbose_name': 'Incoming Mail', 'verbose_name_plural': 'Incoming Mails'},
        ),
        migrations.AlterModelOptions(
            name='outgoingdisposition',
            options={'verbose_name': 'Outgoing Disposition', 'verbose_name_plural': 'Outgoing Dispositions'},
        ),
        migrations.AlterModelOptions(
            name='outgoingmail',
            options={'verbose_name': 'Outgoing Mail', 'verbose_name_plural': 'Outgoing Mails'},
        ),
        migrations.AlterField(
            model_name='agenda',
            name='year',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(2000), app.models.max_value_current_year]),
        ),
    ]
