# Generated by Django 5.0.4 on 2024-04-14 15:19

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_incomingdisposition_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingmail',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d', validators=[app.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='outgoingmail',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d', validators=[app.models.validate_file_extension]),
        ),
    ]
