# Generated by Django 5.0.4 on 2024-04-14 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_incomingmail_date_alter_outgoingmail_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingmail',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='outgoingmail',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
