# Generated by Django 5.0.4 on 2024-04-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_incomingmail_date_alter_outgoingmail_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingdisposition',
            name='information',
            field=models.PositiveSmallIntegerField(choices=[('', 'Select Information'), (0, 'Processing'), (1, 'Accepted'), (2, 'Rejected')]),
        ),
        migrations.AlterField(
            model_name='outgoingdisposition',
            name='information',
            field=models.PositiveSmallIntegerField(choices=[('', 'Select Information'), (0, 'Processing'), (1, 'Accepted'), (2, 'Rejected')]),
        ),
    ]
